# Form implementation generated from reading ui file 'c:\Users\bosto\OneDrive - Moreton Bay Colleges\yr12\Digitial\IA2\code\ia2\other.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
